/**
 * Reads .env (or .env.example) and writes src/environments/environment.local.ts.
 * Run via: node scripts/generate-env.js
 */
const fs = require('fs');
const path = require('path');
const { loadEnv } = require('./parse-env');

const FRONTEND_DIR = path.resolve(__dirname, '..');
const OUTPUT = path.join(FRONTEND_DIR, 'src', 'environments', 'environment.local.ts');

const REQUIRED_KEYS = [
  'FIREBASE_API_KEY',
  'FIREBASE_AUTH_DOMAIN',
  'FIREBASE_PROJECT_ID',
  'FIREBASE_STORAGE_BUCKET',
  'FIREBASE_MESSAGING_SENDER_ID',
  'FIREBASE_APP_ID',
  'GOOGLE_CLIENT_ID',
];

const { env, source } = loadEnv(FRONTEND_DIR);

if (!source) {
  console.error('\x1b[31m[generate-env] Neither .env nor .env.example found. Aborting.\x1b[0m');
  process.exit(1);
}

const missing = REQUIRED_KEYS.filter(k => !env[k]);
if (missing.length) {
  console.error(`\x1b[31m[generate-env] Missing required keys in ${source}: ${missing.join(', ')}\x1b[0m`);
  process.exit(1);
}

const isLocal = (env.IS_LOCAL || 'true').toLowerCase() === 'true';

const output = `/**
 * AUTO-GENERATED by scripts/generate-env.js — do not edit.
 * Source: ${source}
 */

export const environment = {
  firebase: {
    apiKey: '${env.FIREBASE_API_KEY}',
    authDomain: '${env.FIREBASE_AUTH_DOMAIN}',
    projectId: '${env.FIREBASE_PROJECT_ID}',
    storageBucket: '${env.FIREBASE_STORAGE_BUCKET}',
    messagingSenderId: '${env.FIREBASE_MESSAGING_SENDER_ID}',
    appId: '${env.FIREBASE_APP_ID}',
    measurementId: '${env.FIREBASE_MEASUREMENT_ID || ''}',
  },
  production: false,
  isLocal: ${isLocal},
  backendURL: '/api',
  EMAIL_REGEX:
    /^(([^<>()[\\]\\\\.,;:\\s@"]+(\\.[^<>()[\\]\\\\.,;:\\s@"]+)*)|(".+"))@((\\[\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$/,
  ADMIN: 'admin',
  GOOGLE_CLIENT_ID: '${env.GOOGLE_CLIENT_ID}',
};
`;

fs.writeFileSync(OUTPUT, output, 'utf8');
console.log(`\x1b[32m[generate-env] Wrote ${path.relative(FRONTEND_DIR, OUTPUT)} from ${source}\x1b[0m`);
